### PR TITLE
Add support for dark/light theme.

### PR DESCRIPTION
**Pull request by pgroot91**
This branch was created to address a couple of things (Sorry for the mass in commits):

**Changes in this branch:**
- Adding a light/dark theme for Katalon Recorder. (Change your theme settings eg on Windows)
- Adding new Katalon Branding for Katalon Recorder.
- Small alignment fixes in various areas of the Katalon Recorder.
- Reworked the console section a bit. 

Still some stuff can be polished up a bit! This can be addressed in feature patches/releases. 

Please let me know what you think and have it a go @devalex88 

**Some ideas for the future:**
- Like to merge some of the menu items on the top right together. 
--- Merging all available settings together in one section.
--- Help section.
--- Katalon section with products and solutions. 
- Adding a theme switcher to switch dark/light mode ignoring your theme settings of your PC

### CODE REVIEW

**Comment by pgroot91** [comment]
I noticed now that i uploaded the full branding package from Katalon.

Let me clean this up before merging this to master if you consider this pr for a release 👍

**Comment by devalex88** [comment]
Many thanks for the PR! I will review this and publish the change next week.

**Comment by pgroot91** [comment]
@devalex88 👍 cleaned the pr a bit and katalon branding images that are not used are now removed.

**Comment by devalex88** [comment]
@pgroot91 Sorry it took so long! The new version has been released to the store. There were so many good changes - thank you a lot for this PR ❤️ .

**Pull request merged**
